//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBasket.Persistence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBasket.Persistence.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER TABLE [dbo].[ProductOption] DROP CONSTRAINT [FK_57]
        ///GO
        ///ALTER TABLE [dbo].[ProductOption] DROP CONSTRAINT [FK_132]
        ///GO
        ///ALTER TABLE [dbo].[ProductDetail] DROP CONSTRAINT [FK_129]
        ///GO
        ///ALTER TABLE [dbo].[Option] DROP CONSTRAINT [FK_51]
        ///GO
        ///ALTER TABLE [dbo].[Basket] DROP CONSTRAINT [FK_135]
        ///GO
        ///ALTER TABLE [dbo].[Basket] DROP CONSTRAINT [FK_109]
        ///GO
        ////****** Object:  Table [dbo].[ProductOption]    Script Date: 9.01.2021 03:57:06 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedData_Down {
            get {
                return ResourceManager.GetString("SeedData_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[Customer] ON 
        ///
        ///INSERT [dbo].[Customer] ([CustomerId], [FirstName], [LastName], [Email], [Address]) VALUES (1, N&apos;Yakup&apos;, N&apos;Önal&apos;, N&apos;yakuponall@hotmail.com&apos;, N&apos;Kayseri&apos;)
        ///INSERT [dbo].[Customer] ([CustomerId], [FirstName], [LastName], [Email], [Address]) VALUES (2, N&apos;Adem&apos;, N&apos;Ayvacık&apos;, N&apos;adem@gmail.com&apos;, N&apos;İstanbul&apos;)
        ///INSERT [dbo].[Customer] ([CustomerId], [FirstName], [LastName], [Email], [Address]) VALUES (3, N&apos;Kazım&apos;, N&apos;Balta&apos;, N&apos;kazım@gmail.com&apos;, N&apos;Ankara&apos;)
        ///INSERT [dbo].[Cu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedData_Up {
            get {
                return ResourceManager.GetString("SeedData_Up", resourceCulture);
            }
        }
    }
}
